$(".title").click(function(e){
		e.preventDefault();
        $(".imgshow").slideToggle();
    });

$(".title_2").click(function(e){
		e.preventDefault();
        $(".imgshow_2").slideToggle();
    });
$(".title_3").on('click',function(e){
		e.preventDefault();
        $(".imgshow_3").slideToggle();
    });
$(".title_4").click(function(e){
		e.preventDefault();
        $(".imgshow_4").slideToggle();
    });
$(".title_5").click(function(e){
		e.preventDefault();
        $(".imgshow_5").slideToggle();
    });